---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: ansible_playbook
  playbook: test/integration/default/playbook/default.yml
  roles_path: <%= %x(echo ../${PWD}) %>
  hosts: all

platforms:
- name: centos-6.8
- name: centos-7.2

suites:
- name: default